// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Auth": {
    "email": "Email",
    "emailPlaceholder": "you@example.com",
    "password": "Password",
    "login": "Sign In",
    "loggingIn": "Signing in...",
    "forgotPassword": "Forgot password?",
    "invalidCredentials": "Invalid email or password",
    "passwordTooShort": "Password must be at least 6 characters",
    "passwordsDontMatch": "Passwords do not match"
  },
  "Nav": {
    "dashboard": "Dashboard",
    "bots": "Bots",
    "backtest": "Backtest",
    "settings": "Settings",
    "apiKeys": "API Keys",
    "billing": "Billing",
    "signOut": "Sign Out"
  },
  "Dashboard": {
    "title": "Dashboard",
    "totalBalance": "Total Balance",
    "activeBots": "Active Bots",
    "todayPnl": "Today P&L",
    "recentTrades": "Recent Trades",
    "noTrades": "No trades yet",
    "sessions": "Sessions",
    "portfolioValue": "Portfolio Value",
    "strategies": "Strategies",
    "manage": "Manage",
    "viewAll": "View all in dashboard",
    "noStrategies": "No strategies configured yet.",
    "createStrategy": "Create a strategy"
  },
  "Bots": {
    "title": "Trading Bots",
    "create": "Create Bot",
    "start": "Start",
    "stop": "Stop",
    "delete": "Delete",
    "backToBots": "Back to bots",
    "tradingDashboard": "Trading Dashboard",
    "balances": "Balances",
    "openOrders": "Open Orders",
    "closedOrders": "Closed Orders",
    "recentTrades": "Recent Trades",
    "strategies": "Strategies",
    "activeCount": "{count} active",
    "maker": "Maker",
    "locked": "{amount} locked",
    "errorBanner": "Container encountered an error. Try restarting it.",
    "stoppedBanner": "Container is stopped. Start it to see live trading data.",
    "noBalances": "No non-zero balances",
    "startToSeeData": "Start the container to see live data",
    "noOpenOrders": "No open orders",
    "noClosedOrders": "No closed orders",
    "noTrades": "No trades yet",
    "status": {
      "running": "Running",
      "stopped": "Stopped",
      "error": "Error"
    },
    "strategyStatus": {
      "running": "running",
      "idle": "idle"
    },
    "loading": "Loading...",
    "noStrategies": "No strategies yet. Create one to get started.",
    "userContainer": "User Container",
    "dashboard": "Dashboard",
    "remove": "Remove",
    "removeConfirm": "Are you sure you want to remove this strategy?",
    "strategiesCount": "{count} strategies",
    "containerName": "Container: bbgo-{id}",
    "name": "Name",
    "mode": {
      "live": "Live",
      "paper": "Paper",
      "backtest": "Backtest"
    },
    "sessionRoles": "Session Roles",
    "cancel": "Cancel",
    "creating": "Creating...",
    "futures": "Futures",
    "strategyParams": "Strategy Parameters",
    "errorLoading": "Failed to load data. Please try again.",
    "save": "Save",
    "saving": "Saving...",
    "testnet": "Testnet",
    "containerLogs": "Container Logs"
  },
  "Backtest": {
    "title": "Backtest",
    "run": "Run Backtest",
    "results": "Results",
    "totalProfit": "Total Profit",
    "maxDrawdown": "Max Drawdown",
    "sharpeRatio": "Sharpe Ratio",
    "winRate": "Win Rate",
    "trades": "Trades",
    "noResults": "No backtest results yet",
    "strategy": "Strategy",
    "exchange": "Exchange",
    "startDate": "Start Date",
    "endDate": "End Date",
    "running": "Running...",
    "backtestOutput": "Backtest Output",
    "backtestDuration": "Backtest may take 30-60 seconds depending on date range..."
  },
  "Settings": {
    "apiKeys": {
      "title": "Exchange API Keys",
      "add": "Add API Key",
      "exchange": "Exchange",
      "apiKey": "API Key",
      "apiSecret": "API Secret",
      "testnet": "Use Testnet",
      "passphrase": "Passphrase",
      "empty": "No API keys configured.",
      "delete": "Delete",
      "verified": "Verified",
      "verificationFailed": "Verification failed"
    }
  },
  "Errors": {
    "serverError": "Server error. Please try again.",
    "fetchFailed": "Failed to fetch data. Please try again."
  }
};
export default messages;