// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Auth": {
    "email": "Email",
    "emailPlaceholder": "you@example.com",
    "password": "Password",
    "login": "Sign In",
    "loggingIn": "Signing in...",
    "forgotPassword": "Forgot password?",
    "invalidCredentials": "Invalid email or password",
    "passwordTooShort": "Password must be at least 6 characters",
    "passwordsDontMatch": "Passwords do not match"
  },
  "Nav": {
    "dashboard": "Dashboard",
    "bots": "Bots",
    "backtest": "Backtest",
    "settings": "Settings",
    "apiKeys": "API Keys",
    "billing": "Billing",
    "signOut": "Sign Out"
  },
  "Dashboard": {
    "title": "Dashboard",
    "totalBalance": "Total Balance",
    "activeBots": "Active Bots",
    "todayPnl": "Today P&L",
    "recentTrades": "Recent Trades",
    "noTrades": "No trades yet"
  },
  "Bots": {
    "title": "Trading Bots",
    "create": "Create Bot",
    "start": "Start",
    "stop": "Stop",
    "delete": "Delete",
    "status": {
      "running": "Running",
      "stopped": "Stopped",
      "error": "Error"
    },
    "strategyParams": "Strategy Parameters",
    "mode": {
      "live": "Live",
      "paper": "Paper",
      "backtest": "Backtest"
    }
  },
  "Backtest": {
    "title": "Backtest",
    "run": "Run Backtest",
    "results": "Results",
    "totalProfit": "Total Profit",
    "maxDrawdown": "Max Drawdown",
    "sharpeRatio": "Sharpe Ratio",
    "winRate": "Win Rate",
    "trades": "Trades",
    "noResults": "No backtest results yet"
  },
  "Settings": {
    "apiKeys": {
      "title": "Exchange API Keys",
      "add": "Add API Key",
      "exchange": "Exchange",
      "apiKey": "API Key",
      "apiSecret": "API Secret",
      "testnet": "Use Testnet",
      "passphrase": "Passphrase",
      "empty": "No API keys configured.",
      "delete": "Delete",
      "verified": "Verified",
      "verificationFailed": "Verification failed"
    }
  },
  "Errors": {
    "serverError": "Server error. Please try again.",
    "fetchFailed": "Failed to fetch data. Please try again."
  }
};
export default messages;