// Code generated by web/scripts/gen_strategy_types.mjs. DO NOT EDIT.
// Source: web/src/lib/bbgo/strategies.ts STRATEGY_SCHEMAS
//
// Regenerate: cd web && node scripts/gen_strategy_types.mjs

package main

// StrategyMeta holds metadata for a strategy type.
type StrategyMeta struct {
	ID                string
	Label             string
	Description       string
	Category          string
	SupportedExchanges []string
	LiveOnly          bool
	CrossExchange     bool
	SessionRoles      []SessionRoleConfig
}


// --- Grid Strategies ---

type GridConfig struct {
	Symbol string `json:"symbol"`
	GridNumber float64 `json:"gridNumber"`
	UpperPrice float64 `json:"upperPrice"`
	LowerPrice float64 `json:"lowerPrice"`
	Quantity float64 `json:"quantity"`
	ProfitSpread float64 `json:"profitSpread"`
	Side string `json:"side,omitempty"`
	CatchUp *bool `json:"catchUp,omitempty"`
}

type Grid2Config struct {
	Symbol string `json:"symbol"`
	GridNumber float64 `json:"gridNumber"`
	UpperPrice float64 `json:"upperPrice"`
	LowerPrice float64 `json:"lowerPrice"`
	Quantity *float64 `json:"quantity,omitempty"`
	ProfitSpread *float64 `json:"profitSpread,omitempty"`
	QuoteInvestment *float64 `json:"quoteInvestment,omitempty"`
	Compound *bool `json:"compound,omitempty"`
	EarnBase *bool `json:"earnBase,omitempty"`
	TriggerPrice *float64 `json:"triggerPrice,omitempty"`
	StopLossPrice *float64 `json:"stopLossPrice,omitempty"`
	TakeProfitPrice *float64 `json:"takeProfitPrice,omitempty"`
}

type BollgridConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	GridNumber float64 `json:"gridNumber"`
	GridPips float64 `json:"gridPips"`
	Quantity float64 `json:"quantity"`
	ProfitSpread float64 `json:"profitSpread"`
}

type XhedgegridConfig struct {
	Symbol string `json:"symbol"`
	GridNumber float64 `json:"gridNumber"`
	UpperPrice float64 `json:"upperPrice"`
	LowerPrice float64 `json:"lowerPrice"`
	Quantity float64 `json:"quantity"`
	ProfitSpread *float64 `json:"profitSpread,omitempty"`
	QuoteInvestment *float64 `json:"quoteInvestment,omitempty"`
	Compound *bool `json:"compound,omitempty"`
	EarnBase *bool `json:"earnBase,omitempty"`
}


// --- Market Maker Strategies ---

type BollmakerConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	BidQuantity float64 `json:"bidQuantity"`
	AskQuantity float64 `json:"askQuantity"`
	Spread *float64 `json:"spread,omitempty"`
	MinProfitSpread *float64 `json:"minProfitSpread,omitempty"`
	MaxExposurePosition *float64 `json:"maxExposurePosition,omitempty"`
	DisableShort *bool `json:"disableShort,omitempty"`
	TradeInBand *bool `json:"tradeInBand,omitempty"`
	ShadowProtection *bool `json:"shadowProtection,omitempty"`
}

type LinregmakerConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	BidQuantity float64 `json:"bidQuantity"`
	AskQuantity float64 `json:"askQuantity"`
	Spread *float64 `json:"spread,omitempty"`
	MinProfitSpread *float64 `json:"minProfitSpread,omitempty"`
	MaxExposurePosition *float64 `json:"maxExposurePosition,omitempty"`
}

type RsmakerConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	BidQuantity float64 `json:"bidQuantity"`
	AskQuantity float64 `json:"askQuantity"`
	Spread *float64 `json:"spread,omitempty"`
	MinProfitSpread *float64 `json:"minProfitSpread,omitempty"`
	MaxExposurePosition *float64 `json:"maxExposurePosition,omitempty"`
}

type FixedmakerConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	Quantity float64 `json:"quantity"`
	HalfSpread float64 `json:"halfSpread"`
	DryRun *bool `json:"dryRun,omitempty"`
}

type FmakerConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	Quantity float64 `json:"quantity"`
	Spread *float64 `json:"spread,omitempty"`
	MinProfitSpread *float64 `json:"minProfitSpread,omitempty"`
}

type ScmakerConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	Window float64 `json:"window"`
	K *float64 `json:"k,omitempty"`
	NumOfLiquidityLayers float64 `json:"numOfLiquidityLayers"`
	MaxExposure *float64 `json:"maxExposure,omitempty"`
	MinProfit *float64 `json:"minProfit,omitempty"`
}

type AudacitymakerConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	Window float64 `json:"window"`
}

type LiquiditymakerConfig struct {
	Symbol string `json:"symbol"`
	NumOfLiquidityLayers float64 `json:"numOfLiquidityLayers"`
	Spread *float64 `json:"spread,omitempty"`
	AskLiquidityAmount *float64 `json:"askLiquidityAmount,omitempty"`
	BidLiquidityAmount *float64 `json:"bidLiquidityAmount,omitempty"`
	LiquidityPriceRange *float64 `json:"liquidityPriceRange,omitempty"`
	MaxPositionExposure *float64 `json:"maxPositionExposure,omitempty"`
}


// --- Trend Following Strategies ---

type SupertrendConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	SupertrendMultiplier *float64 `json:"supertrendMultiplier,omitempty"`
	Quantity float64 `json:"quantity"`
	Leverage *float64 `json:"leverage,omitempty"`
	TakeProfitAtrMultiplier *float64 `json:"takeProfitAtrMultiplier,omitempty"`
	StopByReversedSupertrend *bool `json:"stopByReversedSupertrend,omitempty"`
	DrawGraph *bool `json:"drawGraph,omitempty"`
}

type EmacrossConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	FastWindow float64 `json:"fastWindow"`
	SlowWindow float64 `json:"slowWindow"`
	Quantity float64 `json:"quantity"`
}

type TrendtraderConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	Quantity float64 `json:"quantity"`
	Leverage *float64 `json:"leverage,omitempty"`
}

type AtrpinConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	Window float64 `json:"window"`
	Multiplier *float64 `json:"multiplier,omitempty"`
	Quantity float64 `json:"quantity"`
}

type DriftConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	Window float64 `json:"window"`
	Quantity float64 `json:"quantity"`
	Stoploss *float64 `json:"stoploss,omitempty"`
	UseStopLoss *bool `json:"useStopLoss,omitempty"`
	UseAtr *bool `json:"useAtr,omitempty"`
	PredictOffset *float64 `json:"predictOffset,omitempty"`
	MinInterval string `json:"MinInterval,omitempty"`
	AtrWindow *float64 `json:"atrWindow,omitempty"`
	GenerateGraph *bool `json:"generateGraph,omitempty"`
}

type ElliottwaveConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	Stoploss *float64 `json:"stoploss,omitempty"`
	MinInterval string `json:"minInterval,omitempty"`
	WindowATR *float64 `json:"windowATR,omitempty"`
	WindowQuick *float64 `json:"windowQuick,omitempty"`
	WindowSlow *float64 `json:"windowSlow,omitempty"`
	UseHeikinAshi *bool `json:"useHeikinAshi,omitempty"`
	DrawGraph *bool `json:"drawGraph,omitempty"`
}

type FactorzooConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	Window float64 `json:"window"`
}


// --- Mean Reversion Strategies ---

type PivotshortConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	Quantity float64 `json:"quantity"`
	Leverage *float64 `json:"leverage,omitempty"`
}

type SwingConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	BaseQuantity float64 `json:"baseQuantity"`
	MinChange *float64 `json:"minChange,omitempty"`
	MovingAverageType string `json:"movingAverageType,omitempty"`
	MovingAverageWindow *float64 `json:"movingAverageWindow,omitempty"`
}

type EwoDgtrdConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	SigWin *float64 `json:"sigWin,omitempty"`
	Stoploss *float64 `json:"stoploss,omitempty"`
	UseHeikinAshi *bool `json:"useHeikinAshi,omitempty"`
	CciStochFilterHigh *float64 `json:"cciStochFilterHigh,omitempty"`
	CciStochFilterLow *float64 `json:"cciStochFilterLow,omitempty"`
	EwoChangeFilterHigh *float64 `json:"ewoChangeFilterHigh,omitempty"`
	EwoChangeFilterLow *float64 `json:"ewoChangeFilterLow,omitempty"`
}

type HarmonicConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	Window float64 `json:"window"`
	Quantity float64 `json:"quantity"`
	DrawGraph *bool `json:"drawGraph,omitempty"`
}

type IrrConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	Window float64 `json:"window"`
	Quantity float64 `json:"quantity"`
	DrawGraph *bool `json:"drawGraph,omitempty"`
}


// --- DCA Strategies ---

type DcaConfig struct {
	Symbol string `json:"symbol"`
	InvestmentInterval string `json:"investmentInterval,omitempty"`
	Budget float64 `json:"budget"`
	BudgetPeriod string `json:"budgetPeriod,omitempty"`
}

type Dca2Config struct {
	Symbol string `json:"symbol"`
	QuoteInvestment float64 `json:"quoteInvestment"`
	MaxOrderCount float64 `json:"maxOrderCount"`
	PriceDeviation *float64 `json:"priceDeviation,omitempty"`
	TakeProfitRatio *float64 `json:"takeProfitRatio,omitempty"`
}

type Dca3Config struct {
	Symbol string `json:"symbol"`
	QuoteInvestment float64 `json:"quoteInvestment"`
	MaxOrderCount float64 `json:"maxOrderCount"`
	PriceDeviation *float64 `json:"priceDeviation,omitempty"`
	TakeProfitRatio *float64 `json:"takeProfitRatio,omitempty"`
}

type AutobuyConfig struct {
	Symbol string `json:"symbol"`
	Schedule string `json:"schedule"`
	Quantity *float64 `json:"quantity,omitempty"`
	Amount *float64 `json:"amount,omitempty"`
	MinBaseBalance *float64 `json:"minBaseBalance,omitempty"`
	DryRun *bool `json:"dryRun,omitempty"`
}

type ScheduleConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	Side string `json:"side"`
	Quantity float64 `json:"quantity"`
	UseLimitOrder *bool `json:"useLimitOrder,omitempty"`
	MinBaseBalance *float64 `json:"minBaseBalance,omitempty"`
	MaxBaseBalance *float64 `json:"maxBaseBalance,omitempty"`
}


// --- Volatility Strategies ---

type FlashcrashConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	GridNumber float64 `json:"gridNumber"`
	Percentage float64 `json:"percentage"`
	BaseQuantity float64 `json:"baseQuantity"`
}

type XvsConfig struct {
	Symbol string `json:"symbol"`
	Quantity float64 `json:"quantity"`
	MaxExposure *float64 `json:"maxExposure,omitempty"`
	VolumeInterval string `json:"volumeInterval,omitempty"`
	VolumeThreshold *float64 `json:"volumeThreshold,omitempty"`
	Stoploss *float64 `json:"stoploss,omitempty"`
}


// --- Other Strategies ---

type WallConfig struct {
	Symbol string `json:"symbol"`
	Side string `json:"side"`
	Interval string `json:"interval,omitempty"`
	Quantity float64 `json:"quantity"`
	NumLayers float64 `json:"numLayers"`
	LayerSpread *float64 `json:"layerSpread,omitempty"`
}

type SentinelConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	Threshold *float64 `json:"threshold,omitempty"`
	Window *float64 `json:"window,omitempty"`
	NumSamples *float64 `json:"numSamples,omitempty"`
	Proportion *float64 `json:"proportion,omitempty"`
}

type RandomConfig struct {
	Symbol string `json:"symbol"`
	Quantity *float64 `json:"quantity,omitempty"`
	Schedule string `json:"schedule,omitempty"`
	DryRun *bool `json:"dryRun,omitempty"`
}

type RebalanceConfig struct {
	Schedule string `json:"schedule"`
	QuoteCurrency string `json:"quoteCurrency"`
	Threshold *float64 `json:"threshold,omitempty"`
	DryRun *bool `json:"dryRun,omitempty"`
}


// --- Indicator Strategies ---

type TechsignalConfig struct {
	Symbol string `json:"symbol"`
}


// --- Utility Strategies ---

type AutoborrowConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	MinMarginLevel *float64 `json:"minMarginLevel,omitempty"`
	MaxMarginLevel *float64 `json:"maxMarginLevel,omitempty"`
	AutoRepayWhenDeposit *bool `json:"autoRepayWhenDeposit,omitempty"`
}

type ConvertConfig struct {
	Symbol string `json:"symbol"`
	From string `json:"from"`
	To string `json:"to"`
}

type Deposit2transferConfig struct {
	Assets string `json:"assets"`
	Interval string `json:"interval,omitempty"`
	IgnoreDust *bool `json:"ignoreDust,omitempty"`
}

type SupportConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	Quantity float64 `json:"quantity"`
}


// --- Cross-Exchange Strategies ---

type XmakerConfig struct {
	Symbol string `json:"symbol"`
	Spread *float64 `json:"spread,omitempty"`
	Quantity float64 `json:"quantity"`
	UpdateInterval string `json:"updateInterval,omitempty"`
	HedgeInterval string `json:"hedgeInterval,omitempty"`
}

type XbalanceConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
}

type XalignConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
}

type XpremiumConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
	Quantity float64 `json:"quantity"`
}

type XfixedmakerConfig struct {
	Symbol string `json:"symbol"`
	HalfSpread *float64 `json:"halfSpread,omitempty"`
	Quantity float64 `json:"quantity"`
}

type XnavConfig struct {
	Symbol string `json:"symbol"`
	Interval string `json:"interval,omitempty"`
}

type XgapConfig struct {
	Symbol string `json:"symbol"`
	Quantity float64 `json:"quantity"`
}

type XdepthmakerConfig struct {
	Symbol string `json:"symbol"`
	Quantity float64 `json:"quantity"`
	Spread *float64 `json:"spread,omitempty"`
}

type XfundingConfig struct {
	Symbol string `json:"symbol"`
	Quantity float64 `json:"quantity"`
}

type Xfundingv2Config struct {
	Symbol string `json:"symbol"`
	Quantity float64 `json:"quantity"`
}

var StrategyRegistry = map[string]StrategyMeta{
	"grid": {
		ID:                "grid",
		Label:             "Grid",
		Description:       "Classic grid trading with fixed price boundaries",
		Category:          "grid",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"grid2": {
		ID:                "grid2",
		Label:             "Grid v2",
		Description:       "Advanced grid trading with compound, stop-loss, take-profit and auto-range",
		Category:          "grid",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"bollgrid": {
		ID:                "bollgrid",
		Label:             "Bollinger Grid",
		Description:       "Grid trading with Bollinger Band dynamic boundaries",
		Category:          "grid",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"bollmaker": {
		ID:                "bollmaker",
		Label:             "Bollinger Maker",
		Description:       "Market making with Bollinger Band neutral zone and trend-following exposure control",
		Category:          "maker",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"linregmaker": {
		ID:                "linregmaker",
		Label:             "Linear Regression Maker",
		Description:       "Market making with linear regression trend indicators for dynamic spread and exposure",
		Category:          "maker",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"rsmaker": {
		ID:                "rsmaker",
		Label:             "RS Maker",
		Description:       "Market making with Relative Strength indicator for trend-aware order placement",
		Category:          "maker",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"fixedmaker": {
		ID:                "fixedmaker",
		Label:             "Fixed Maker",
		Description:       "Simple market making with fixed spread and quantity",
		Category:          "maker",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"fmaker": {
		ID:                "fmaker",
		Label:             "F Maker",
		Description:       "Flexible market maker with advanced order management",
		Category:          "maker",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"scmaker": {
		ID:                "scmaker",
		Label:             "SC Maker",
		Description:       "Market making with Bollinger Band safety and grid scaling",
		Category:          "maker",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          true,
		CrossExchange:     false,
	},
	"supertrend": {
		ID:                "supertrend",
		Label:             "Supertrend",
		Description:       "Trend following with Supertrend indicator and optional DEMA confirmation",
		Category:          "trend",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          true,
		CrossExchange:     false,
	},
	"emacross": {
		ID:                "emacross",
		Label:             "EMA Cross",
		Description:       "Trend following with fast/slow EMA crossover signals",
		Category:          "trend",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"trendtrader": {
		ID:                "trendtrader",
		Label:             "Trend Trader",
		Description:       "Trend line breakout trading with configurable entry methods",
		Category:          "trend",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"pivotshort": {
		ID:                "pivotshort",
		Label:             "Pivot Short",
		Description:       "Short trades based on pivot point breakouts with RSI filter",
		Category:          "mean-reversion",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"swing": {
		ID:                "swing",
		Label:             "Swing",
		Description:       "Swing trading with moving average crossover and minimum change filter",
		Category:          "mean-reversion",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"dca": {
		ID:                "dca",
		Label:             "Dollar Cost Average",
		Description:       "Periodic fixed-amount purchases on schedule",
		Category:          "dca",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"dca2": {
		ID:                "dca2",
		Label:             "DCA v2",
		Description:       "Advanced DCA with take-profit, price deviation, and max order controls",
		Category:          "dca",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          true,
		CrossExchange:     false,
	},
	"dca3": {
		ID:                "dca3",
		Label:             "DCA v3",
		Description:       "DCA v2 variant with additional recovery options",
		Category:          "dca",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          true,
		CrossExchange:     false,
	},
	"autobuy": {
		ID:                "autobuy",
		Label:             "Auto Buy",
		Description:       "Automatic periodic buying with fixed amount",
		Category:          "dca",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          true,
		CrossExchange:     false,
	},
	"flashcrash": {
		ID:                "flashcrash",
		Label:             "Flash Crash",
		Description:       "Buy during flash crashes with percentage-based grid placement",
		Category:          "volatility",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"wall": {
		ID:                "wall",
		Label:             "Wall",
		Description:       "Place large wall orders at configurable levels",
		Category:          "other",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          true,
		CrossExchange:     false,
	},
	"sentinel": {
		ID:                "sentinel",
		Label:             "Sentinel",
		Description:       "Monitor and alert on price movements and market conditions",
		Category:          "other",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          true,
		CrossExchange:     false,
	},
	"random": {
		ID:                "random",
		Label:             "Random",
		Description:       "Random trading for testing and benchmarking",
		Category:          "other",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"rebalance": {
		ID:                "rebalance",
		Label:             "Rebalance",
		Description:       "Periodic portfolio rebalancing across assets",
		Category:          "other",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          true,
		CrossExchange:     false,
	},
	"xhedgegrid": {
		ID:                "xhedgegrid",
		Label:             "Hedge Grid",
		Description:       "Grid trading with hedge mode support and compound/profit options",
		Category:          "grid",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"audacitymaker": {
		ID:                "audacitymaker",
		Label:             "Audacity Maker",
		Description:       "Order flow based market making with per-trade order management",
		Category:          "maker",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"liquiditymaker": {
		ID:                "liquiditymaker",
		Label:             "Liquidity Maker",
		Description:       "Advanced market maker with layered liquidity and mid-price EMA tracking",
		Category:          "maker",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          true,
		CrossExchange:     false,
	},
	"atrpin": {
		ID:                "atrpin",
		Label:             "ATR Pin",
		Description:       "ATR-based pinbar detection with trend-following entry and exit management",
		Category:          "trend",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"drift": {
		ID:                "drift",
		Label:             "Drift",
		Description:       "Drift MA strategy with linear regression prediction, ATR stop-loss and trailing exits",
		Category:          "trend",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"elliottwave": {
		ID:                "elliottwave",
		Label:             "Elliott Wave",
		Description:       "Elliott Wave oscillator with ATR stop-loss, Heikin-Ashi and trailing exits",
		Category:          "trend",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"factorzoo": {
		ID:                "factorzoo",
		Label:             "Factor Zoo",
		Description:       "Multi-factor linear strategy with momentum and exit management",
		Category:          "trend",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          true,
		CrossExchange:     false,
	},
	"ewo_dgtrd": {
		ID:                "ewo_dgtrd",
		Label:             "EWO Divergence",
		Description:       "Elliott Wave Oscillator divergence trading with CCI-Stochastic filters",
		Category:          "mean-reversion",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"harmonic": {
		ID:                "harmonic",
		Label:             "Harmonic",
		Description:       "SHARK harmonic pattern detection with quantity-based entries",
		Category:          "mean-reversion",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"irr": {
		ID:                "irr",
		Label:             "Negative Return Rate",
		Description:       "Mean reversion using negative return rate indicator with quantity-based entries",
		Category:          "mean-reversion",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"schedule": {
		ID:                "schedule",
		Label:             "Scheduled Order",
		Description:       "Submit orders on schedule with optional moving average conditions",
		Category:          "dca",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"xvs": {
		ID:                "xvs",
		Label:             "Volume Surge",
		Description:       "Trade on volume surge signals with EMA and pivot high confirmation",
		Category:          "volatility",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          true,
		CrossExchange:     false,
	},
	"techsignal": {
		ID:                "techsignal",
		Label:             "Tech Signal",
		Description:       "Technical signal detection with support levels and funding rate monitoring",
		Category:          "indicator",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     false,
	},
	"autoborrow": {
		ID:                "autoborrow",
		Label:             "Auto Borrow/Repay",
		Description:       "Automatically manage margin borrowing and repayment based on margin level",
		Category:          "utility",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget"},
		LiveOnly:          true,
		CrossExchange:     false,
	},
	"convert": {
		ID:                "convert",
		Label:             "Asset Converter",
		Description:       "Automatically convert one asset to another (e.g., dust conversion)",
		Category:          "utility",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          true,
		CrossExchange:     false,
	},
	"deposit2transfer": {
		ID:                "deposit2transfer",
		Label:             "Deposit Transfer",
		Description:       "Automatically detect deposits and transfer assets to trading account",
		Category:          "utility",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          true,
		CrossExchange:     false,
	},
	"support": {
		ID:                "support",
		Label:             "Support Monitor",
		Description:       "Detect support/resistance levels and trigger protective orders",
		Category:          "utility",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          true,
		CrossExchange:     false,
	},
	"xmaker": {
		ID:                "xmaker",
		Label:             "Cross-Exchange Market Maker",
		Description:       "Market maker that hedges orders across two exchanges (maker + hedge sessions)",
		Category:          "cross-exchange",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     true,
		SessionRoles: []SessionRoleConfig{
			{Name: "maker", Exchange: "", Futures: false},
			{Name: "hedge", Exchange: "", Futures: true},
		},
	},
	"xbalance": {
		ID:                "xbalance",
		Label:             "Cross-Exchange Balance",
		Description:       "Balance rebalancing across two exchange sessions",
		Category:          "cross-exchange",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     true,
		SessionRoles: []SessionRoleConfig{
			{Name: "source", Exchange: "", Futures: false},
			{Name: "target", Exchange: "", Futures: false},
		},
	},
	"xalign": {
		ID:                "xalign",
		Label:             "Cross-Exchange Align",
		Description:       "Align positions across spot and futures sessions with arbitrage logic",
		Category:          "cross-exchange",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     true,
		SessionRoles: []SessionRoleConfig{
			{Name: "spot", Exchange: "", Futures: false},
			{Name: "futures", Exchange: "", Futures: true},
		},
	},
	"xpremium": {
		ID:                "xpremium",
		Label:             "Cross-Exchange Premium",
		Description:       "Trade premium/discount between spot and futures across exchanges",
		Category:          "cross-exchange",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          true,
		CrossExchange:     true,
		SessionRoles: []SessionRoleConfig{
			{Name: "spot", Exchange: "", Futures: false},
			{Name: "futures", Exchange: "", Futures: true},
		},
	},
	"xfixedmaker": {
		ID:                "xfixedmaker",
		Label:             "Cross-Exchange Fixed Maker",
		Description:       "Fixed spread market maker with cross-exchange hedging",
		Category:          "cross-exchange",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     true,
		SessionRoles: []SessionRoleConfig{
			{Name: "maker", Exchange: "", Futures: false},
			{Name: "hedge", Exchange: "", Futures: true},
		},
	},
	"xnav": {
		ID:                "xnav",
		Label:             "Cross-Exchange NAV",
		Description:       "Net asset value tracking and rebalancing across sessions",
		Category:          "cross-exchange",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          true,
		CrossExchange:     true,
		SessionRoles: []SessionRoleConfig{
			{Name: "spot", Exchange: "", Futures: false},
			{Name: "futures", Exchange: "", Futures: true},
		},
	},
	"xgap": {
		ID:                "xgap",
		Label:             "Cross-Exchange Gap",
		Description:       "Detect and trade price gaps across two exchanges",
		Category:          "cross-exchange",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     true,
		SessionRoles: []SessionRoleConfig{
			{Name: "sessionA", Exchange: "", Futures: false},
			{Name: "sessionB", Exchange: "", Futures: false},
		},
	},
	"xdepthmaker": {
		ID:                "xdepthmaker",
		Label:             "Cross-Exchange Depth Maker",
		Description:       "Depth-based market maker with cross-exchange order book comparison",
		Category:          "cross-exchange",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     true,
		SessionRoles: []SessionRoleConfig{
			{Name: "maker", Exchange: "", Futures: false},
			{Name: "hedge", Exchange: "", Futures: true},
		},
	},
	"xfunding": {
		ID:                "xfunding",
		Label:             "Funding Rate Arbitrage",
		Description:       "Capture funding rate differentials between spot and perpetual futures",
		Category:          "cross-exchange",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     true,
		SessionRoles: []SessionRoleConfig{
			{Name: "spot", Exchange: "", Futures: false},
			{Name: "futures", Exchange: "", Futures: true},
		},
	},
	"xfundingv2": {
		ID:                "xfundingv2",
		Label:             "Funding Rate Arbitrage v2",
		Description:       "Enhanced funding rate arbitrage with improved position management",
		Category:          "cross-exchange",
		SupportedExchanges: []string{"binance", "okex", "bybit", "bitget", "kucoin"},
		LiveOnly:          false,
		CrossExchange:     true,
		SessionRoles: []SessionRoleConfig{
			{Name: "spot", Exchange: "", Futures: false},
			{Name: "futures", Exchange: "", Futures: true},
		},
	},
}

// NewStrategyConfig returns a typed config instance for the given strategy ID.
func NewStrategyConfig(id string) any {
	switch id {
	case "grid":
		return &GridConfig{}
	case "grid2":
		return &Grid2Config{}
	case "bollgrid":
		return &BollgridConfig{}
	case "bollmaker":
		return &BollmakerConfig{}
	case "linregmaker":
		return &LinregmakerConfig{}
	case "rsmaker":
		return &RsmakerConfig{}
	case "fixedmaker":
		return &FixedmakerConfig{}
	case "fmaker":
		return &FmakerConfig{}
	case "scmaker":
		return &ScmakerConfig{}
	case "supertrend":
		return &SupertrendConfig{}
	case "emacross":
		return &EmacrossConfig{}
	case "trendtrader":
		return &TrendtraderConfig{}
	case "pivotshort":
		return &PivotshortConfig{}
	case "swing":
		return &SwingConfig{}
	case "dca":
		return &DcaConfig{}
	case "dca2":
		return &Dca2Config{}
	case "dca3":
		return &Dca3Config{}
	case "autobuy":
		return &AutobuyConfig{}
	case "flashcrash":
		return &FlashcrashConfig{}
	case "wall":
		return &WallConfig{}
	case "sentinel":
		return &SentinelConfig{}
	case "random":
		return &RandomConfig{}
	case "rebalance":
		return &RebalanceConfig{}
	case "xhedgegrid":
		return &XhedgegridConfig{}
	case "audacitymaker":
		return &AudacitymakerConfig{}
	case "liquiditymaker":
		return &LiquiditymakerConfig{}
	case "atrpin":
		return &AtrpinConfig{}
	case "drift":
		return &DriftConfig{}
	case "elliottwave":
		return &ElliottwaveConfig{}
	case "factorzoo":
		return &FactorzooConfig{}
	case "ewo_dgtrd":
		return &EwoDgtrdConfig{}
	case "harmonic":
		return &HarmonicConfig{}
	case "irr":
		return &IrrConfig{}
	case "schedule":
		return &ScheduleConfig{}
	case "xvs":
		return &XvsConfig{}
	case "techsignal":
		return &TechsignalConfig{}
	case "autoborrow":
		return &AutoborrowConfig{}
	case "convert":
		return &ConvertConfig{}
	case "deposit2transfer":
		return &Deposit2transferConfig{}
	case "support":
		return &SupportConfig{}
	case "xmaker":
		return &XmakerConfig{}
	case "xbalance":
		return &XbalanceConfig{}
	case "xalign":
		return &XalignConfig{}
	case "xpremium":
		return &XpremiumConfig{}
	case "xfixedmaker":
		return &XfixedmakerConfig{}
	case "xnav":
		return &XnavConfig{}
	case "xgap":
		return &XgapConfig{}
	case "xdepthmaker":
		return &XdepthmakerConfig{}
	case "xfunding":
		return &XfundingConfig{}
	case "xfundingv2":
		return &Xfundingv2Config{}
	default:
		return &map[string]any{}
	}
}
