sessions:
  binance:
    exchange: binance
    envVarPrefix: BINANCE
    publicOnly: true
  okex:
    exchange: okex
    envVarPrefix: OKEX
    publicOnly: true
  bybit:
    exchange: bybit
    envVarPrefix: BYBIT
    publicOnly: true
  bitget:
    exchange: bitget
    envVarPrefix: BITGET
    publicOnly: true
  kucoin:
    exchange: kucoin
    envVarPrefix: KUCOIN
    publicOnly: true
  max:
    exchange: max
    envVarPrefix: MAX
    publicOnly: true
  bitfinex:
    exchange: bitfinex
    envVarPrefix: BITFINEX
    publicOnly: true
